###
post https://backend2.gridxmeter.com/insertMeterData
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzU1NDIxMCwiZXhwIjoxNzEzNTU3ODEwfQ.JZ9aI69CkEsSQkb4HSV9CBLkg4Y7u2ycFT7PmFHSxCA  

{
 "data":[
     "DRN": "0260694812784",
    "Surname": "Jose",
    "Name": "Dino",
    "Suburb": "Havana",
    "City": "Wndhoek",
    "Streetname": "Tugela Steet",
    "Housenumber": "20",
    "Simnumber": "0811234567",
    "Usercategory": "Home",
    "Meterlng": "-22.521021538121",
    "Meterlat": "17.0324874862621",
    "Transformerlng": "-22.5208258027464",
    "Transformerlat": "17.033259962460",
    "TransformerDRN": "0260000000090"
 ]
}
###
get http://localhost:4000/activeInactiveMeters
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzU1NDIxMCwiZXhwIjoxNzEzNTU3ODEwfQ.JZ9aI69CkEsSQkb4HSV9CBLkg4Y7u2ycFT7PmFHSxCA  
###