get http://localhost:4000/allProcessedTokensByDRN0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDY0MjExMCwiZXhwIjoxNzE0NjQ1NzEwfQ.6gK4DeQVg1oGvQiuDBC1gSAs9fHhykkPQde0z3DcxzI
###
get http://localhost:4000/meterDataByDRN0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTE4MjE0MCwiZXhwIjoxNzE1MTg1NzQwfQ.dIr96hdHY0j0GkoIu-Cw0oD2jXltphVvp9WuqFxsSZg
###
GET http://localhost:4000/meterWeekAndMonthData0260066545641 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDQ4ODQyMiwiZXhwIjoxNzE0NDkyMDIyfQ.gSC5KpjcmSPIEn8_SQbNOeUiyH8rP2Cw5B9B2rQicnM
###
get http://localhost:4000/notificationsTypesByDRN/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMzg3MzUyMiwiZXhwIjoxNzEzODc3MTIyfQ.56wMXXfSoqxjWaTX5IXNhCdkx80XIXvXB4FOV3krukA