get http://localhost:4000/settings/meterResetHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###2
get http://localhost:4000/settings/meterCalibrationHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###3
get http://localhost:4000/settings/meterControlHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###4
get http://localhost:4000/settings/meterStateHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###5
get http://localhost:4000/settings/heaterControlHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###6
get http://localhost:4000/settings/heaterStateHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###7
get http://localhost:4000/settings/stsTokenHistory/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg
###8
get http://localhost:4000/settings/tokenInformation/0260066545641
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjQ5Nzg0MSwiZXhwIjoxNzE2NTAxNDQxfQ.fESWv0WwhLhPVrS__eYaA8DtSQdDJC1PTKzubK-14vg