post http://localhost:4000/suburb-time-periods 
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNDY0MjExMCwiZXhwIjoxNzE0NjQ1NzEwfQ.6gK4DeQVg1oGvQiuDBC1gSAs9fHhykkPQde0z3DcxzI

{
    "suburbs":[
     "Academia" 
    ]
}
###
post http://localhost:4000/search-by-weekly-power 
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU5NzY4NSwiZXhwIjoxNzE1NjAxMjg1fQ.m7GTYqRiJqA1bfFCVz1Th2_wqsExADkM6qRt6JbUI7o

{
    "suburbs":[
     "Freedom Land" 
    ]
}
###
post https://backend2.gridxmeter.com/search-by-monthly-power
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU5NzY4NSwiZXhwIjoxNzE1NjAxMjg1fQ.m7GTYqRiJqA1bfFCVz1Th2_wqsExADkM6qRt6JbUI7o

{
    "suburbs":[
     "Groot Aub" 
    ]
}

###

