###Voltage
GET https://backend2.gridxmeter.com/systemSettings/getVoltageThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateVoltageThresholds 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      "newUpperThreshold"  : 300,
      "newLowerThreshold" : 10 ,
      "type" : "Critical",
      "IsActive" : false
}
###Current
get https://backend2.gridxmeter.com/systemSettings/getCurrentThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateCurrentThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      "newUpperThreshold"  : 50,
      "newLowerThreshold" : 10 ,
      "type" : "Critical",
      "IsActive" : false
}
###ActivePower
get https://backend2.gridxmeter.com/systemSettings/getActivePowerThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateActivePowerThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      "newUpperThreshold"  : 30,
      "newLowerThreshold" : 5 ,
      "type" : "Warning",
      "IsActive" : true
} 
###
###ReactivePower
get https://backend2.gridxmeter.com/systemSettings/getReactivePowerThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateReactivePowerThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      "newUpperThreshold"  : 30,
      "newLowerThreshold" : 5 ,
      "type" : "Critical",
      "IsActive" : true
}

###ApparentPower
get https://backend2.gridxmeter.com/systemSettings/getApparentPowerThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateApparentPowerThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      "newUpperThreshold"  : 40,
      "newLowerThreshold" : 20 ,
      "type" : "Warning",
      "IsActive" : true
}

###PowerFactor
get https://backend2.gridxmeter.com/systemSettings/getPowerFactorThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updatePowerFactorThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      
      "newLowerThreshold" : 0.70 ,
      "type" : "Critical",
      "IsActive" : false
}

###Temperature
get https://backend2.gridxmeter.com/systemSettings/getTemperatureThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateTemperatureThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      
      "newUpperThreshold" : 80,
      "type" : "Critical",
      "IsActive" : true
}
###Units
get https://backend2.gridxmeter.com/systemSettings/getLowEnergyUnitsThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateLowEnergyUnitsThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      "newUpperThreshold"  : 300,
      "newLowerThreshold" : 100 ,
      "type" : "Critical",
      "IsActive" : true
}
###FrequncyDeviation
get https://backend2.gridxmeter.com/systemSettings/getFrequencyDeviationThresholds 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ
###
put https://backend2.gridxmeter.com/systemSettings/updateFrequencyDeviationThresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNjkwMzQ3NSwiZXhwIjoxNzE2OTA3MDc1fQ.QzrPiKBmlGCwr2RZ68Tpcl1WL4f8ooMVQxAD_CAN0eQ

{
      
      "newLowerThreshold" : 0.70 ,
      "type" : "Warning",
      "IsActive" : true
}