
###
post http://localhost:4000/signin  
Content-Type: application/json

{
    "Email": "admin@pulsar.com",
    "Password": "Admin@123"
    
    
    
}

###

post http://localhost:4000/adminSignup
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2Nlc3NMZXZlbCI6IjEiLCJpYXQiOjE3MDg0MzI0OTMsImV4cCI6MTcwODQzNjA5M30.PfpDvdx7RY8DNgfzAJ5c80b0zAm8aZvFPq_8vrzyXnk
Content-Type: application/json

{
    "Username": "admin25",
    "Password": "12345678",
    "FirstName": "King",
    "LastName": "Hiholike",
    "Email": "king@gmail.com",
    "IsActive": 1,
    "RoleName": "Developer",
    "AccessLevel": 1
}


###
post http://localhost:4000/forgot-password

{
"Email": "admin@pulsarelectronic.com"

}

###
post http://localhost:4000/reset-password

{
"newPassword": "undefined",
"confirm_password": "undefined"

}

authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW1wb3JhcnlQYXNzd29yZCI6IjlqOGoxcnc0IiwiaWF0IjoxNjk1MDcyODc3LCJleHAiOjE2OTUwNzY0Nzd9.Obl8pXhoXwe94b162j-LQM6Pwt2x5Ez85qrgh5Ddr9c
Content-Type: application/json
###

get http://localhost:4000/protected
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjEsIkFjY2Vzc0xldmVsIjoxLCJpYXQiOjE2OTcwODk1NDd9.e0w2iP1HWpyuztzeDI7LIFsNkL0W71me_Y-xDFr5xEI
Content-Type: application/json
###
get http://localhost:4000/reset-password
###
get http://localhost:4000/profile/1
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjEsIkFjY2Vzc0xldmVsIjoxLCJpYXQiOjE2OTcwODk1NDd9.e0w2iP1HWpyuztzeDI7LIFsNkL0W71me_Y-xDFr5xEI
###
get http://localhost:4000/allAdmins
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2Nlc3NMZXZlbCI6IjEiLCJpYXQiOjE3MTE0NDQyMTQsImV4cCI6MTcxMTQ0NzgxNH0.zCP2fLu_oB4Q-yKoywjOFoijQroA5EYEkyYvOsFfA9c
Content-Type: application/json
###

post http://localhost:4000/UserUpdate/1

{
"FirstName":"Update update",
"Email":"etangoking90@gmail.com"

}
###

post http://localhost:4000/AdminUpdate/1

###
delete http://localhost:4000/deleteUser/3

Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjMwLCJBY2Nlc3NMZXZlbCI6MSwiaWF0IjoxNjk3MDM4ODkzfQ.ib2Gbym7p6iC_p5gSdY3lNarXeyzsnX_8dWvoMUZbRA
Content-Type: application/jsonn


###
get http://localhost:4000/protected
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsIkFjY2Vzc0xldmVsIjoxLCJpYXQiOjE2OTgyMzAxMDEsImV4cCI6MTY5ODIzMzcwMX0.f1RkZQuh7UZa_lPE3WelM3wukLcf7DjD0LY9byYnLi0

###
post http://localhost:4000/updateStatus/10

###
get http://localhost:4000/meter_change

###
get http://localhost:4000/active_state_count

###
get http://localhost:4000/inactive_state_count

####

get http://localhost:4000/adminAuth/accessLevel
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxMjA1OTEyMiwiZXhwIjoxNzEyMDYyNzIyfQ.Ubt8RnUdq-ZO61Yjspu9kVPLDhEX-HqvnaMTWwDQDwE
Content-Type: application/jsonn
