

get http://localhost:4000/profile/1

###
get http://localhost:4000/allAdmins
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZG1pbl9JRCI6MTAsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoiMSIsImlhdCI6MTcxNTU4NzUyOSwiZXhwIjoxNzE1NTkxMTI5fQ.ZArv7-sEsq2go5tB6vXHq9A-2iE-t8E0ClWLT0_7dP8

###

post http://localhost:4000/UserUpdate/1

{
"FirstName":"Update update",
"Email":"etangoking90@gmail.com"

}
###

post http://localhost:4000/AdminUpdate/1

###
delete http://localhost:4000/deleteUser/3

Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjMwLCJBY2Nlc3NMZXZlbCI6MSwiaWF0IjoxNjk3MDM4ODkzfQ.ib2Gbym7p6iC_p5gSdY3lNarXeyzsnX_8dWvoMUZbRA
Content-Type: application/jsonn



